id: PFEF628EF
initial_creation_type: input
source_metadata:
  title: Khenchen Tashi Özer Series
  language: en
  description: 'Texts by Khenchen Tashi Özer (mkhan chen bkra shis ''od zer, 1836–1910),
    the renowned disciple of Kongtrul Lodrö Thaye and others:'
  volume:
    95f446eff74f4efda78d4459cff90349:
      title: Advice for Satsa Drupgen
      parent: Advice
created_at: '2022-03-01T00:23:22.342078'
last_modified_at: '2022-03-01T00:23:22.342084'
